server:
  port: 8085
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #配置静态资源
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/
  #配置数据库
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;SelectMethod=cursor;DatabaseName=jimureport
    username: sa
    password: ???
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#Minidao配置
minidao:
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*
#JimuReport[上传配置]
jeecg:
  # local|minio|alioss
  uploadType: oss
  # local
  path:
    #文件路径
    upload: /opt/upload
  # alioss
  oss:
    accessKey: ??
    secretKey: ??
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: jeecgdev
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport: info
