server:
  port: 8085
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS  
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #数据库
  datasource:
    url: jdbc:mysql://${MYSQL-HOST:127.0.0.1}:${MYSQL-PORT:3306}/${MYSQL-DB:jimureport}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Redis配置
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
  # 登录认证配置
  security:
    #是否开启登录认证
    enable: true
    #登录账号和密码
    user:
      name: "admin"
      password: "123456"
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
    template_update_delay: 0
#持久层框架
minidao:
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*
jeecg:
  # local|minio|alioss
  uploadType: local
  # local
  path:
    #文件路径
    upload: /opt/upload
  # alioss
  oss:
    endpoint: ??
    accessKey: ??
    secretKey: ??
    bucketName: jimureport
  # minio
  minio:
    minio_url: http://minio.jeecg.com
    minio_name: ??
    minio_pass: ??
    bucketName: ??
  #大屏报表参数设置
  jmreport:
    # 邮件发送
    mail:
      # 是否开启
      enabled: false
      host: "???"
      sender: "???"
      username: "??@??.com"
      password: "???"
      # 是否开启ssl
      #ssl: true
      # smtp端口
      #port: 465
    # 自动化导出
    automate:
      export:
        # 开启自动导出,默认false
        enable-auto-export: true
        # 非必须，文件过期时间，单位天，默认：30
        expired: 30
        # 非必须，积木报表view页面地址
        #jimu-view-path: "https://???/jmreport/view/"
        # 非必须，下载的报表的存放目录(服务器上的目录)
        #download-path: "/???/???"
    #多租户模式，默认值为空(created:按照创建人隔离、tenant:按照租户隔离)
    saasMode:
    # 签名密钥
    signatureSecret: dd05f1c54d63749eda95f9fa6d49v442a
    # 平台上线安全配置
    firewall:
      # 数据源安全 (开启后，不允许使用平台数据源、SQL解析加签并且不允许查询数据库)
      dataSourceSafe: false
      # SQL解析安全 false: 数据库解析(默认,稳定性好) true: jsqlparser解析(不走数据库,安全级别高) v2.2.1+新增
      #sqlParseSafe: true
      # 低代码开发模式（dev:开发模式，prod:发布模式—关闭在线报表设计功能，分配角色admin、lowdeveloper可放开限制）
      lowCodeMode: dev
      # sql注入检查级别（strict:严格, basic:简单校验, none:不校验）
      sqlInjectionLevel: basic
    # 高德地图Api配置(v2.1.3+ BI新增高德地图)
    gao-de-api:
      # 应用key
      api-key: ??
      # 应用秘钥
      secret-key: ??
    # 展示列数
    col: 100
    # 展示行数
    row: 200
    #自定义API接口的前缀 #{api_base_path}和#{domainURL}的值
    apiBasePath: http://192.168.1.11:8085
    #数据量最大限制（适用于无分页模式、打印全部等场景，默认：100000）v2.2.1+新增
    #说明：1.无分页模式-查询时最多返回该数量的记录 2.打印全部-最多处理该数量的记录
    max-data-rows: 100000
    pageSize:
      - 10
      - 20
      - 30
      - 40
    ai:
      jeecg-host: http://localhost:8080/jeecgboot/
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport: info
